#!/usr/bin/env python3
"""Summarize V338 scene-only control assets without treating PPO as trained evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


STATIC = ("validation_selected_static", "feasible_static_projected")
DYNAMIC = ("aoi", "round_robin", "random")
ORDINARY = "oracle_loss_mean"
MACRO = "oracle_loss_macro_subtype_event_staticnorm"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-dir", action="append", required=True, type=Path)
    parser.add_argument("--out-dir", required=True, type=Path)
    args = parser.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    for run_dir in args.run_dir:
        metrics = pd.read_csv(run_dir / "v2_custom_ppo_metrics.csv")
        metadata_path = run_dir / "dataset_validation" / "synthetic_metadata.json"
        metadata = json.loads(metadata_path.read_text())
        static = metrics[metrics.policy.isin(STATIC)]
        dynamic = metrics[metrics.policy.isin(DYNAMIC)]
        rows.append(
            {
                "seed": int(metadata["seed"]),
                "event_coverage_target": float(metadata["blowing_snow_event_coverage_target"]),
                "event_coverage_actual": float(metadata["blowing_snow_event_coverage_actual"]),
                "storm_regime_fraction": float(metadata["storm_regime_fraction"]),
                "event_cluster_count": int(metadata["event_cluster_count"]),
                "particle_rate": float(metadata["event_subtype_particle_rate"]),
                "flux_rate": float(metadata["event_subtype_flux_rate"]),
                "thermal_rate": float(metadata["event_subtype_thermal_rate"]),
                "static_best_ordinary": float(static[ORDINARY].min()),
                "dynamic_best_ordinary": float(dynamic[ORDINARY].min()),
                "static_best_macro": float(static[MACRO].min()),
                "dynamic_best_macro": float(dynamic[MACRO].min()),
                "dynamic_minus_static_ordinary": float(static[ORDINARY].min() - dynamic[ORDINARY].min()),
                "dynamic_minus_static_macro": float(static[MACRO].min() - dynamic[MACRO].min()),
                "custom_ppo_is_trained": False,
            }
        )

    table = pd.DataFrame(rows).sort_values("seed")
    table.to_csv(args.out_dir / "scene_control_seed_metrics.csv", index=False)
    mean_ordinary = float(table["dynamic_minus_static_ordinary"].mean())
    mean_macro = float(table["dynamic_minus_static_macro"].mean())
    ordinary_wins = int((table["dynamic_minus_static_ordinary"] > 0).sum())
    macro_wins = int((table["dynamic_minus_static_macro"] > 0).sum())
    lines = [
        "# V338 recalibrated-scene control",
        "",
        "This is a scene-only readiness screen. The one-step custom_ppo row was "
        "generated by the control wrapper and is explicitly not treated as trained evidence.",
        "",
        f"- Seeds: {len(table)} ({', '.join(str(int(x)) for x in table.seed)})",
        "- Scene change: target event coverage 0.70 with stratified subtype probabilities "
        "(1/3, 1/3, 1/3).",
        "- Physical channel configuration, effective costs, budget 1.75, startup budget 2.15, "
        "minimum dwell 6, and online observables are unchanged.",
        f"- Best original dynamic versus best static: ordinary {ordinary_wins}/{len(table)} "
        f"wins, mean margin {mean_ordinary:+.6f}; macro {macro_wins}/{len(table)} wins, "
        f"mean margin {mean_macro:+.6f}.",
        "- Decision: retain this scene for a matched trained wave only if the event and "
        "subtype distributions remain physically plausible in the manifest; no PPO claim "
        "is made from this control screen.",
        "",
        table.to_string(index=False),
    ]
    (args.out_dir / "summary.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
