#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

# Single-scene bounded pilot. Forecast-value targets are generated only at
# states visited by the current PPO policy; final execution remains label free.
SEEDS_OVERRIDE="${SEEDS_OVERRIDE:-1303}" \
GPU_IDS="${GPU_IDS:-0}" \
POLICY_SEED_OFFSET="${POLICY_SEED_OFFSET:-12000}" \
SCENE_PREFIX_OVERRIDE=v120_full_intensity_context_gate_dev \
RUN_PREFIX_OVERRIDE="${RUN_PREFIX_OVERRIDE:-v124_onpolicy_forecast_value_pilot}" \
EVENT_SUBTYPE_CONTEXT_LATENT_STRENGTH_OVERRIDE=1.0 \
TOTAL_TIMESTEPS_OVERRIDE="${TOTAL_TIMESTEPS_OVERRIDE:-20480}" \
BC_PRETRAIN_STEPS_OVERRIDE="${BC_PRETRAIN_STEPS_OVERRIDE:-4096}" \
BC_PRETRAIN_EPOCHS_OVERRIDE="${BC_PRETRAIN_EPOCHS_OVERRIDE:-20}" \
BC_PRETRAIN_TARGET_MODE_OVERRIDE=forecast_value_regression \
AWBC_TEACHER_MODE_OVERRIDE=oracle_greedy \
GREEDY_LOOKAHEAD_STEPS_OVERRIDE=8 \
AWBC_COEF_OVERRIDE=0 \
SUBTYPE_AUX_COEF_OVERRIDE=0.3 \
CONTEXT_FUSION_MODE_OVERRIDE=subtype_moe \
TEMPORAL_ENCODER_OVERRIDE=1 \
TEMPORAL_HIDDEN_DIM_OVERRIDE=64 \
CHECKPOINT_SELECTION_INTERVAL_UPDATES=5 \
CHECKPOINT_SELECTION_SCORE_OVERRIDE=max_static_ratio \
FORECAST_VALUE_AUX_COEF_OVERRIDE="${FORECAST_VALUE_AUX_COEF_OVERRIDE:-0.05}" \
FORECAST_VALUE_AUX_STRIDE_OVERRIDE="${FORECAST_VALUE_AUX_STRIDE_OVERRIDE:-64}" \
FORECAST_VALUE_AUX_LOOKAHEAD_STEPS_OVERRIDE=8 \
bash scripts/run_v116_intensity_temporal_forecastbc_ckptppo_20260823.sh
