#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

COMMON_RANDOM_NUMBERS=1 \
SEEDS_OVERRIDE="${SEEDS_OVERRIDE:-1651 1652 1653 1654 1655}" \
RUN_PREFIX_OVERRIDE=v165_persistent_quality_scene_dev \
CONTEXT_OUT_OVERRIDE=reports/aggregate/v165_persistent_quality_context_gate_20260826 \
CHANNEL_QUALITY_ENABLED_OVERRIDE=1 \
CHANNEL_QUALITY_DEGRADED_COVERAGE_OVERRIDE=0.25 \
CHANNEL_QUALITY_MIN_DURATION_STEPS_OVERRIDE=48 \
CHANNEL_QUALITY_MAX_DURATION_STEPS_OVERRIDE=96 \
CHANNEL_QUALITY_MIN_GAP_STEPS_OVERRIDE=24 \
CHANNEL_QUALITY_DEGRADED_VALUE_OVERRIDE=0.2 \
CHANNEL_QUALITY_REPORT_NOISE_STD_OVERRIDE=0.02 \
SENSOR_QUALITY_MAX_NOISE_MULTIPLIER_OVERRIDE=6.0 \
SENSOR_QUALITY_AVAILABILITY_FLOOR_OVERRIDE=0.2 \
bash scripts/run_v137_generic_physical_scene_gate_20260826.sh "${1:-all}"
