#!/usr/bin/env bash
set -euo pipefail

# Offline diagnostic only. Receding labels are generated on policy-training and
# validation partitions; final l4 traces were already generated by V216.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PYTHON="${PYTHON:-$HOME/.conda/envs/darts/bin/python}"
RUN_PREFIX="${RUN_PREFIX:-v213_duration_balanced_scene_dev}"
RUN_SUFFIX="${RUN_SUFFIX:-b1p85_20260822}"
OUT_ROOT="${OUT_ROOT:-reports/aggregate/v217_duration_balanced_l4_learnability_20260828}"
read -r -a SEEDS <<< "${SEEDS_OVERRIDE:-2301 2302 2303 2304 2305}"

mkdir -p "$OUT_ROOT" logs
pids=()
for idx in "${!SEEDS[@]}"; do
  seed="${SEEDS[$idx]}"
  run_dir="reports/${RUN_PREFIX}_seed${seed}_${RUN_SUFFIX}"
  (
    export CUDA_VISIBLE_DEVICES="$idx"
    "$PYTHON" scripts/99_v32_receding_upper.py \
      --run-dir "$run_dir" --partition rl_train \
      --output-subdir receding_oracle_l4_rl_train_trace \
      --receding-oracle-lookahead-steps 4 --device cuda
    "$PYTHON" scripts/99_v32_receding_upper.py \
      --run-dir "$run_dir" --partition validation \
      --output-subdir receding_oracle_l4_validation_trace \
      --receding-oracle-lookahead-steps 4 --device cuda
  ) >"logs/v217_l4_learnability_seed${seed}.log" 2>&1 &
  pids+=("$!")
done
for pid in "${pids[@]}"; do
  wait "$pid"
done

run_dirs=()
for seed in "${SEEDS[@]}"; do
  run_dirs+=("reports/${RUN_PREFIX}_seed${seed}_${RUN_SUFFIX}")
done
"$PYTHON" scripts/102_v32_receding_trace_learnability.py \
  --run-dirs "${run_dirs[@]}" \
  --trace-prefix receding_oracle_l4 \
  --output-dir "$OUT_ROOT/learnability"
