#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export RUN_PREFIX="${RUN_PREFIX:-v31_metpair_backbone_context_ortholinear_balancedobjective_scenebal1}"
export BUDGET_LABEL="${BUDGET_LABEL:-h075ctxolscbal1}"
export DATE_TAG="${DATE_TAG:-20260621}"

# SCENEBAL-1 keeps the TEMPORAL-1 PPO/teacher/lead mechanism and the
# met+one-specialist sensor geometry. It changes the simulator/target contract
# exposed by seed95: the raw step objective should no longer be dominated by a
# fixed met_station_core+fc4_flux shortcut.
export PARTICLE_PROB="${PARTICLE_PROB:-0.38}"
export FLUX_PROB="${FLUX_PROB:-0.24}"
export THERMAL_PROB="${THERMAL_PROB:-0.38}"

export SUBTYPE_LATENT_ALPHA="${SUBTYPE_LATENT_ALPHA:-0.55}"
export PARTICLE_LATENT_DIAMETER_SCALE_MM="${PARTICLE_LATENT_DIAMETER_SCALE_MM:-0.48}"
export PARTICLE_LATENT_VELOCITY_SCALE_MS="${PARTICLE_LATENT_VELOCITY_SCALE_MS:-6.4}"
export FLUX_MULTIPLIER="${FLUX_MULTIPLIER:-2.6}"
export FLUX_LATENT_SIGMA="${FLUX_LATENT_SIGMA:-0.0}"
export FLUX_LATENT_LINEAR_SCALE="${FLUX_LATENT_LINEAR_SCALE:-0.0016}"
export FLUX_LATENT_LINEAR_OFFSET="${FLUX_LATENT_LINEAR_OFFSET:-1.35}"
export FLUX_LATENT_LINEAR_CLIP="${FLUX_LATENT_LINEAR_CLIP:-2.6}"
export THERMAL_LATENT_SURFACE_SCALE_C="${THERMAL_LATENT_SURFACE_SCALE_C:-5.2}"
export THERMAL_SURFACE_DROP_C="${THERMAL_SURFACE_DROP_C:-4.8}"
export THERMAL_AIR_TEMP_DROP_C="${THERMAL_AIR_TEMP_DROP_C:-1.8}"

export EVENT_SUBTYPE_PARTICLE_REWARD_MULTIPLIER="${EVENT_SUBTYPE_PARTICLE_REWARD_MULTIPLIER:-1.45}"
export EVENT_SUBTYPE_FLUX_REWARD_MULTIPLIER="${EVENT_SUBTYPE_FLUX_REWARD_MULTIPLIER:-0.75}"
export EVENT_SUBTYPE_THERMAL_REWARD_MULTIPLIER="${EVENT_SUBTYPE_THERMAL_REWARD_MULTIPLIER:-1.50}"

export TARGET_WEIGHTS="${TARGET_WEIGHTS:-0.08 0.20 0.08 0.0 0.0 0.0 6.0 36.0 36.0}"
export SUBTYPE_PARTICLE_TARGET_WEIGHTS="${SUBTYPE_PARTICLE_TARGET_WEIGHTS:-0.0 0.0 0.08 0.0 0.0 0.0 0.5 90.0 90.0}"
export SUBTYPE_FLUX_TARGET_WEIGHTS="${SUBTYPE_FLUX_TARGET_WEIGHTS:-0.0 0.0 0.04 0.0 0.0 0.0 8.0 6.0 6.0}"
export SUBTYPE_THERMAL_TARGET_WEIGHTS="${SUBTYPE_THERMAL_TARGET_WEIGHTS:-0.18 70.0 0.08 0.0 0.0 0.0 0.2 0.8 0.8}"

bash scripts/run_v31_metpair_backbone_context_ortholinear_balancedobjective_temporal1_seed_sweep_20260621.sh "$@"

