#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

PY="${PY:-/home/zhangzhuyu/.conda/envs/darts/bin/python}"
read -r -a SEEDS <<< "${SEEDS_OVERRIDE:-1501 1502 1503 1504 1505}"
read -r -a GPU_LIST <<< "${GPU_IDS:-0 1 2 3 4}"
SCENE_PREFIX="${SCENE_PREFIX_OVERRIDE:-v138_generic_physical_statefix_gate_dev}"
RUN_PREFIX="${RUN_PREFIX_OVERRIDE:-v139_generic_physical_pdppo_dev}"
LOG_DIR="${LOG_DIR_OVERRIDE:-logs/v139_generic_physical_pdppo}"
SENSOR_CFG=configs/sensors/windblown_sensors_flexible_subset_v6_physical_channels.yaml
mkdir -p "$LOG_DIR"
pids=()

for i in "${!SEEDS[@]}"; do
  seed="${SEEDS[$i]}"
  (
    export CUDA_VISIBLE_DEVICES="${GPU_LIST[$((i % ${#GPU_LIST[@]}))]}"
    export RUN_PREFIX CONTROL_SOURCE_RUN_DIR="reports/${SCENE_PREFIX}_seed${seed}_b1p75_20260822"
    export POLICY_SEED="$((seed + 18000))"
    export SENSOR_CFG TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS_OVERRIDE:-20480}" TRUTH_STEPS=36000 LOOKBACK=20
    export EXCLUDE_SUBTYPE_LATENTS_FROM_STATE=1
    export EVENT_COVERAGE=0.55 MIN_DURATION=20 MAX_DURATION=64 MIN_GAP=12
    export EVENT_MICROSTRUCTURE_SIGMA=0.12 EVENT_MICROSTRUCTURE_ALPHA=0.15
    export EVENT_PARTICLE_MICROSTRUCTURE_CORRELATION=0.0
    export EVENT_SUBTYPE_PARTICLE_MIN_PARSIVEL_AVAILABILITY="${EVENT_SUBTYPE_PARTICLE_MIN_PARSIVEL_AVAILABILITY_OVERRIDE:-0.8}"
    export EVENT_SUBTYPE_ASSIGNMENT=stratified EVENT_SUBTYPE_LATENT_ALPHA=0.15
    export PARTICLE_LATENT_DIAMETER_SCALE=0.28 PARTICLE_LATENT_VELOCITY_SCALE=4.8
    export FLUX_LATENT_SIGMA=2.0 THERMAL_LATENT_SURFACE_SCALE=2.4
    export EVENT_SUBTYPE_CONTEXT_LEAD_STEPS=12 EVENT_SUBTYPE_CONTEXT_NOISE_STD=0.02
    export EVENT_SUBTYPE_CONTEXT_LATENT_STRENGTH=1.0
    export ORACLE_EPOCHS=10 ORACLE_FULL_OPEN_REPEAT=3 ORACLE_CANDIDATE_MASK_REPEAT=2
    export ORACLE_SUBTYPE_TEACHER_REPEAT=0 ORACLE_INFERENCE_DEVICE=cuda
    export BUDGET=1.75 STARTUP_BUDGET=2.15 BUDGET_LABEL=b1p75
    export TARGET_WEIGHTS='1 1 1 1 1 1 1 1 1'
    export CHANNEL_QUALITY_ENABLED="${CHANNEL_QUALITY_ENABLED_OVERRIDE:-0}"
    export CHANNEL_QUALITY_DEGRADED_COVERAGE="${CHANNEL_QUALITY_DEGRADED_COVERAGE_OVERRIDE:-0.0}"
    export CHANNEL_QUALITY_MIN_DURATION_STEPS="${CHANNEL_QUALITY_MIN_DURATION_STEPS_OVERRIDE:-12}"
    export CHANNEL_QUALITY_MAX_DURATION_STEPS="${CHANNEL_QUALITY_MAX_DURATION_STEPS_OVERRIDE:-48}"
    export CHANNEL_QUALITY_MIN_GAP_STEPS="${CHANNEL_QUALITY_MIN_GAP_STEPS_OVERRIDE:-12}"
    export CHANNEL_QUALITY_DEGRADED_VALUE="${CHANNEL_QUALITY_DEGRADED_VALUE_OVERRIDE:-0.2}"
    export CHANNEL_QUALITY_TRANSITION_STEPS="${CHANNEL_QUALITY_TRANSITION_STEPS_OVERRIDE:-0}"
    export CHANNEL_QUALITY_REPORT_NOISE_STD="${CHANNEL_QUALITY_REPORT_NOISE_STD_OVERRIDE:-0.02}"
    export SENSOR_QUALITY_MAX_NOISE_MULTIPLIER="${SENSOR_QUALITY_MAX_NOISE_MULTIPLIER_OVERRIDE:-1.0}"
    export SENSOR_QUALITY_AVAILABILITY_FLOOR="${SENSOR_QUALITY_AVAILABILITY_FLOOR_OVERRIDE:-1.0}"

    # Forecast-value pretraining and the on-policy auxiliary use only the
    # policy-training partition. They never expose subtype labels at runtime.
    export BC_PRETRAIN_STEPS="${BC_PRETRAIN_STEPS_OVERRIDE:-4096}"
    export BC_PRETRAIN_EPOCHS="${BC_PRETRAIN_EPOCHS_OVERRIDE:-20}"
    export BC_PRETRAIN_LOSS_COEF=1.0
    export BC_PRETRAIN_TARGET_MODE="${BC_PRETRAIN_TARGET_MODE_OVERRIDE:-forecast_value_regression}"
    export BC_SOFT_TEMPERATURE="${BC_SOFT_TEMPERATURE_OVERRIDE:-1.0}"
    export FORECAST_VALUE_AUX_COEF="${FORECAST_VALUE_AUX_COEF_OVERRIDE:-0.5}"
    export FORECAST_VALUE_AUX_STRIDE="${FORECAST_VALUE_AUX_STRIDE_OVERRIDE:-16}"
    export FORECAST_VALUE_AUX_LOOKAHEAD_STEPS=8
    export FORECAST_VALUE_AUX_LOSS="${FORECAST_VALUE_AUX_LOSS_OVERRIDE:-soft_ce}"
    export FORECAST_VALUE_AUX_TEMPERATURE="${FORECAST_VALUE_AUX_TEMPERATURE_OVERRIDE:-0.75}"
    export AWBC_COEF="${AWBC_COEF_OVERRIDE:-0}" AWBC_DECAY_TIMESTEPS=0 AWBC_EVENT_ONLY=0
    export AWBC_LABEL_STRIDE="${AWBC_LABEL_STRIDE_OVERRIDE:-4}"
    export AWBC_TEACHER_MODE=oracle_greedy GREEDY_LOOKAHEAD_STEPS=8
    export SUBTYPE_AUX_COEF=0 SUBTYPE_ACTION_CE_COEF=0 SUBTYPE_LOSS_WEIGHTING=0

    export CONTEXT_FEATURE_DIM="${CONTEXT_FEATURE_DIM_OVERRIDE:-20}" CONTEXT_FUSION_MODE=gated_add
    export TEMPORAL_ENCODER=1 TEMPORAL_HIDDEN_DIM=64
    export TRAINABLE_ACTION_PRIOR=0 NONLINEAR_ACTION_EMBEDDING=1
    export ENT_COEF="${ENT_COEF_OVERRIDE:-0.02}" CHANNEL_MARGINAL_ENTROPY_COEF=0
    export POLICY_INIT_SOURCE="${POLICY_INIT_SOURCE_OVERRIDE:-}"
    export POLICY_CHECKPOINT_SOURCE="${POLICY_CHECKPOINT_SOURCE_OVERRIDE:-}"
    export TRAINING_CONTROL_SOURCE_RUN_DIRS="${TRAINING_CONTROL_SOURCE_RUN_DIRS_OVERRIDE:-}"
    export CHECKPOINT_SELECTION_INTERVAL_UPDATES="${CHECKPOINT_SELECTION_INTERVAL_UPDATES_OVERRIDE:-5}"
    export CHECKPOINT_SELECTION_SCORE=max_static_ratio
    export CHECKPOINT_REQUIRE_VALID_BEHAVIOR="${CHECKPOINT_REQUIRE_VALID_BEHAVIOR_OVERRIDE:-0}"
    export EVALUATION_POLICY_MODE=deterministic
    bash scripts/run_v32_flexible_subset_pilot_20260822.sh "$seed"
  ) >"${LOG_DIR}/seed${seed}.log" 2>&1 &
  pids+=("$!")
done

status=0
for pid in "${pids[@]}"; do
  if ! wait "$pid"; then
    status=1
  fi
done
exit "$status"
