#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

COMMON_RANDOM_NUMBERS=1 \
SEEDS_OVERRIDE="${SEEDS_OVERRIDE:-1701}" \
GPU_IDS="${GPU_IDS:-0}" \
SCENE_PREFIX_OVERRIDE=v170_strong_gradual_quality_scene_dev \
RUN_PREFIX_OVERRIDE=v172_v170_quality_context_utility_pilot \
LOG_DIR_OVERRIDE=logs/v172_v170_quality_context_utility_pilot \
CHANNEL_QUALITY_ENABLED_OVERRIDE=1 \
CHANNEL_QUALITY_DEGRADED_COVERAGE_OVERRIDE=0.25 \
CHANNEL_QUALITY_MIN_DURATION_STEPS_OVERRIDE=24 \
CHANNEL_QUALITY_MAX_DURATION_STEPS_OVERRIDE=64 \
CHANNEL_QUALITY_MIN_GAP_STEPS_OVERRIDE=16 \
CHANNEL_QUALITY_DEGRADED_VALUE_OVERRIDE=0.2 \
CHANNEL_QUALITY_TRANSITION_STEPS_OVERRIDE=8 \
CHANNEL_QUALITY_REPORT_NOISE_STD_OVERRIDE=0.02 \
SENSOR_QUALITY_MAX_NOISE_MULTIPLIER_OVERRIDE=7.0 \
SENSOR_QUALITY_AVAILABILITY_FLOOR_OVERRIDE=0.05 \
CONTEXT_FEATURE_DIM_OVERRIDE=26 \
AWBC_COEF_OVERRIDE=0 \
CHECKPOINT_REQUIRE_VALID_BEHAVIOR_OVERRIDE=1 \
QUALITY_CONTEXT_ACTION_SCORE=1 \
TOTAL_TIMESTEPS_OVERRIDE=20480 \
bash scripts/run_v139_generic_physical_pdppo_dev_20260826.sh
