#!/usr/bin/env bash
set -euo pipefail

# Matched clean CA-PD-PPO development run on the V193 frozen scenes.  The
# online observation remains the forecast state plus alert and channel-quality
# proxies; no context-bandit output or final-test label enters training.
cd "$(dirname "$0")/.."

PY="${PY:-/home/zhangzhuyu/.conda/envs/darts/bin/python}"
DEVICE="${DEVICE:-cuda}"
RUN_PREFIX="${RUN_PREFIX:-v194_v193_ca_pdppo_dev}"

if [[ "$#" -gt 0 ]]; then
  SEEDS=("$@")
else
  SEEDS=(1901)
fi

for seed in "${SEEDS[@]}"; do
  CONTROL_SOURCE_RUN_DIR="reports/v193_event_sensor_independent_scene_dev_seed${seed}_b1p75_20260822" \
  RUN_PREFIX="$RUN_PREFIX" \
  DEVICE="$DEVICE" \
  TOTAL_TIMESTEPS=40960 \
  TRUTH_STEPS=36000 \
  LOOKBACK=20 \
  SENSOR_CFG=configs/sensors/windblown_sensors_flexible_subset_v6_physical_channels.yaml \
  BUDGET=1.75 \
  STARTUP_BUDGET=2.15 \
  BUDGET_LABEL=b1p75 \
  TARGET_WEIGHTS='1 1 1 1 1 1 1 1 1' \
  EVENT_COVERAGE=0.55 \
  MIN_DURATION=20 \
  MAX_DURATION=64 \
  MIN_GAP=12 \
  EVENT_MICROSTRUCTURE_SIGMA=0.12 \
  EVENT_MICROSTRUCTURE_ALPHA=0.15 \
  EVENT_PARTICLE_MICROSTRUCTURE_CORRELATION=0.0 \
  EVENT_SUBTYPE_ASSIGNMENT=stratified \
  EVENT_SUBTYPE_PARTICLE_MIN_PARSIVEL_AVAILABILITY=0.0 \
  EVENT_SUBTYPE_LATENT_ALPHA=0.15 \
  PARTICLE_LATENT_DIAMETER_SCALE=0.28 \
  PARTICLE_LATENT_VELOCITY_SCALE=4.8 \
  FLUX_LATENT_SIGMA=2.0 \
  THERMAL_LATENT_SURFACE_SCALE=2.4 \
  EVENT_SUBTYPE_CONTEXT_LEAD_STEPS=12 \
  EVENT_SUBTYPE_CONTEXT_NOISE_STD=0.02 \
  EVENT_SUBTYPE_CONTEXT_LATENT_STRENGTH=1.0 \
  CHANNEL_QUALITY_ENABLED=1 \
  CHANNEL_QUALITY_DEGRADED_COVERAGE=0.25 \
  CHANNEL_QUALITY_MIN_DURATION_STEPS=24 \
  CHANNEL_QUALITY_MAX_DURATION_STEPS=64 \
  CHANNEL_QUALITY_MIN_GAP_STEPS=16 \
  CHANNEL_QUALITY_DEGRADED_VALUE=0.2 \
  CHANNEL_QUALITY_TRANSITION_STEPS=8 \
  CHANNEL_QUALITY_REPORT_NOISE_STD=0.02 \
  SENSOR_QUALITY_MAX_NOISE_MULTIPLIER=7.0 \
  SENSOR_QUALITY_AVAILABILITY_FLOOR=0.05 \
  EXCLUDE_SUBTYPE_LATENTS_FROM_STATE=1 \
  CONTEXT_FEATURE_DIM=20 \
  CONTEXT_FUSION_MODE=gated_add \
  TRAINABLE_ACTION_PRIOR=0 \
  NONLINEAR_ACTION_EMBEDDING=1 \
  BC_PRETRAIN_STEPS=0 \
  BC_PRETRAIN_EPOCHS=1 \
  BC_PRETRAIN_LOSS_COEF=0 \
  AWBC_COEF=0 \
  SUBTYPE_AUX_COEF=0.3 \
  SUBTYPE_ACTION_CE_COEF=0 \
  SUBTYPE_LOSS_WEIGHTING=0 \
  REWARD_PROXY_MODE=forecast \
  REWARD_LOSS_NORMALIZATION=none \
  COMMON_RANDOM_NUMBERS=1 \
  bash scripts/run_v32_flexible_subset_pilot_20260822.sh "$seed"
done
