#!/usr/bin/env bash
set -euo pipefail

# Horizon-aligned, forecast-value actor initialization for the V227 physical
# grouping. Candidate costs are generated by the already frozen forecaster on
# policy-training starts only; final execution still uses only online nowcasts
# and feasibility masking.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export SEEDS_OVERRIDE="${SEEDS_OVERRIDE:-2491 2492 2493 2494 2495}"
export RUN_PREFIX_OVERRIDE="${RUN_PREFIX_OVERRIDE:-v230_physical_groups_actor_value_dev}"
export FORECAST_VALUE_HEAD=0
export FORECAST_VALUE_AUX_COEF=0.20
export FORECAST_VALUE_AUX_STRIDE=32
export FORECAST_VALUE_AUX_LOOKAHEAD_STEPS=8
export FORECAST_VALUE_AUX_LOSS=smooth_l1
export FORECAST_VALUE_RANKING_COEF=0.10
export GREEDY_LOOKAHEAD_STEPS=8
export BC_PRETRAIN_STEPS_OVERRIDE=4096
export BC_PRETRAIN_EPOCHS_OVERRIDE=4
export BC_PRETRAIN_LOSS_COEF_OVERRIDE=1.0
export BC_PRETRAIN_TARGET_MODE=forecast_value_regression

exec bash scripts/run_v229_physical_groups_nowcast_ppo_20260828.sh
