#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export RUN_PREFIX="${RUN_PREFIX:-v31_metpair_backbone_context_ortholinear_balancedobjective_temporal1}"
export BUDGET_LABEL="${BUDGET_LABEL:-h075ctxoltemp1}"
export DATE_TAG="${DATE_TAG:-20260621}"

# TEMPORAL-1 pivots away from BRG action-fidelity. It keeps PPO and the
# met+specialist sensor baseline, but gives the actor/teacher a longer
# deployable regime lead so PPO can realize the lead-based explicit replay
# headroom seen on seed92.
export INCLUDE_OBSERVABLE_REGIME_BELIEF="${INCLUDE_OBSERVABLE_REGIME_BELIEF:-1}"
export REGIME_BELIEF_LOOKBACK="${REGIME_BELIEF_LOOKBACK:-16}"
export EVENT_GATED_ACTOR="${EVENT_GATED_ACTOR:-1}"
export SUBTYPE_AUX_COEF="${SUBTYPE_AUX_COEF:-5.0}"
export SUBTYPE_AUX_LOOKAHEAD_STEPS="${SUBTYPE_AUX_LOOKAHEAD_STEPS:-16}"
export SUBTYPE_ROUTER_MIN_CONFIDENCE="${SUBTYPE_ROUTER_MIN_CONFIDENCE:-0.70}"
export EVAL_SUBTYPE_ROUTER_MIN_CONFIDENCE="${EVAL_SUBTYPE_ROUTER_MIN_CONFIDENCE:-0.70}"
export ENT_COEF="${ENT_COEF:-0.0075}"

# Close the BRG-3 action-fidelity subdirection.
export SUBTYPE_ACTION_CE_COEF="${SUBTYPE_ACTION_CE_COEF:-0.0}"
export SUBTYPE_ACTION_MARGIN_COEF="${SUBTYPE_ACTION_MARGIN_COEF:-0.0}"
export SUBTYPE_ACTION_MARGIN="${SUBTYPE_ACTION_MARGIN:-0.50}"

export AWBC_TEACHER_MODE="${AWBC_TEACHER_MODE:-subtype_auto}"
export AWBC_TEACHER_AUTO_SCORE_MODE="${AWBC_TEACHER_AUTO_SCORE_MODE:-raw}"
export AWBC_TEACHER_EVENT_LOOKAHEAD_STEPS="${AWBC_TEACHER_EVENT_LOOKAHEAD_STEPS:-16}"
export AWBC_TEACHER_DWELL_STEPS="${AWBC_TEACHER_DWELL_STEPS:-10}"
export ORACLE_SUBTYPE_TEACHER_LOOKAHEAD_STEPS="${ORACLE_SUBTYPE_TEACHER_LOOKAHEAD_STEPS:-16}"
export GREEDY_LOOKAHEAD_STEPS="${GREEDY_LOOKAHEAD_STEPS:-8}"

export SUBTYPE_CONTEXT_LEAD_STEPS="${SUBTYPE_CONTEXT_LEAD_STEPS:-16}"
export SUBTYPE_LATENT_TARGET_LAG_STEPS="${SUBTYPE_LATENT_TARGET_LAG_STEPS:-6}"
export BLOWING_SNOW_LEAD_STEPS="${BLOWING_SNOW_LEAD_STEPS:-10}"
export REPLAY_LEAD_STEPS="${REPLAY_LEAD_STEPS:-0 4 8 12 16}"
export REPLAY_DWELL_STEPS="${REPLAY_DWELL_STEPS:-6 10 16 24}"

export LAMBDA_DUTY_BALANCE="${LAMBDA_DUTY_BALANCE:-0.0}"
export DUTY_SCORE_FEEDBACK="${DUTY_SCORE_FEEDBACK:-0.0}"
export DUTY_HARD_GUARD="${DUTY_HARD_GUARD:-0}"

bash scripts/run_v31_metpair_backbone_context_ortholinear_balancedobjective_seed_sweep_20260620.sh "$@"
