#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

SEEDS_OVERRIDE="${SEEDS_OVERRIDE:-1601}" \
GPU_IDS="${GPU_IDS:-0}" \
SCENE_PREFIX_OVERRIDE=v152_channel_quality_scene_dev \
RUN_PREFIX_OVERRIDE="${RUN_PREFIX_OVERRIDE:-v153_quality_pdppo_pilot}" \
LOG_DIR_OVERRIDE="${LOG_DIR_OVERRIDE:-logs/v153_quality_pdppo_pilot}" \
CHANNEL_QUALITY_ENABLED_OVERRIDE=1 \
CHANNEL_QUALITY_DEGRADED_COVERAGE_OVERRIDE=0.25 \
CHANNEL_QUALITY_MIN_DURATION_STEPS_OVERRIDE=12 \
CHANNEL_QUALITY_MAX_DURATION_STEPS_OVERRIDE=48 \
CHANNEL_QUALITY_MIN_GAP_STEPS_OVERRIDE=12 \
CHANNEL_QUALITY_DEGRADED_VALUE_OVERRIDE=0.2 \
CHANNEL_QUALITY_REPORT_NOISE_STD_OVERRIDE=0.02 \
SENSOR_QUALITY_MAX_NOISE_MULTIPLIER_OVERRIDE=6.0 \
SENSOR_QUALITY_AVAILABILITY_FLOOR_OVERRIDE=0.2 \
TOTAL_TIMESTEPS_OVERRIDE="${TOTAL_TIMESTEPS_OVERRIDE:-20480}" \
bash scripts/run_v139_generic_physical_pdppo_dev_20260826.sh
