#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

PY="${PY:-/home/zhangzhuyu/.conda/envs/darts/bin/python}"
DATE_TAG="${DATE_TAG:-20260620}"
RUN_PREFIX="${RUN_PREFIX:-v31_metpair_backbone_context_ortholinear_balancedobjective}"
BUDGET_LABEL="${BUDGET_LABEL:-h075ctxolbo}"
AUTONOMY_TAG="${AUTONOMY_TAG:-20260621}"
AUTONOMY_HOURS="${AUTONOMY_HOURS:-24}"
WAVE_SIZE="${WAVE_SIZE:-12}"
START_SEED="${START_SEED:-55}"
MIN_FREE_GB="${MIN_FREE_GB:-100}"
SLEEP_BETWEEN_WAVES="${SLEEP_BETWEEN_WAVES:-60}"
BASE_SEED_START="${BASE_SEED_START:-41}"

mkdir -p logs reports/aggregate
END_TS=$(( $(date +%s) + AUTONOMY_HOURS * 3600 ))
NEXT_SEED="$START_SEED"
STATUS_FILE="reports/aggregate/balancedobjective_24h_autonomy_${AUTONOMY_TAG}.md"

log_status() {
  printf '%s\n' "$*" | tee -a "$STATUS_FILE"
}

free_gb() {
  df -BG . | awk 'NR==2 {gsub("G", "", $4); print $4}'
}

seed_args() {
  local end_seed="$1"
  seq "$BASE_SEED_START" "$end_seed" | tr '\n' ' '
}

aggregate_until() {
  local end_seed="$1"
  local seeds
  seeds="$(seed_args "$end_seed")"
  local out_base="reports/aggregate/metpair_backbone_context_ortholinear_balancedobjective_${BASE_SEED_START}_${end_seed}_${AUTONOMY_TAG}"
  log_status ""
  log_status "## Aggregate through seed ${end_seed}"
  log_status "- Started: $(date -Is)"
  "$PY" scripts/72_v31_collect_metpair_strongclaim.py \
    --run-glob "reports/${RUN_PREFIX}_seed*_${BUDGET_LABEL}_${DATE_TAG}" \
    --seeds $seeds \
    --out-dir "${out_base}_macro" \
    2>&1 | tee "logs/bo24_collect_macro_${BASE_SEED_START}_${end_seed}_${AUTONOMY_TAG}.log"
  "$PY" scripts/72_v31_collect_metpair_strongclaim.py \
    --run-glob "reports/${RUN_PREFIX}_seed*_${BUDGET_LABEL}_${DATE_TAG}" \
    --seeds $seeds \
    --router-eval-dir . \
    --out-dir "${out_base}_raw_macro" \
    2>&1 | tee "logs/bo24_collect_raw_macro_${BASE_SEED_START}_${end_seed}_${AUTONOMY_TAG}.log"
  "$PY" scripts/73_v31_collect_oldclaim_gate.py \
    --run-glob "reports/${RUN_PREFIX}_seed*_${BUDGET_LABEL}_${DATE_TAG}" \
    --seeds $seeds \
    --out-dir "${out_base}_oldclaim" \
    2>&1 | tee "logs/bo24_collect_oldclaim_${BASE_SEED_START}_${end_seed}_${AUTONOMY_TAG}.log"
  "$PY" scripts/74_v31_write_balancedobjective_report.py \
    --macro-dir "${out_base}_macro" \
    --raw-macro-dir "${out_base}_raw_macro" \
    --oldclaim-dir "${out_base}_oldclaim" \
    --out-file "${out_base}_oldclaim/BREAKTHROUGH_REPORT.md" \
    --title "V31 Balanced-Objective ${BASE_SEED_START}-${end_seed} Report" \
    --notes "Generated by 24h autonomous runner ${AUTONOMY_TAG}." \
    2>&1 | tee "logs/bo24_write_report_${BASE_SEED_START}_${end_seed}_${AUTONOMY_TAG}.log"
  log_status "- Finished: $(date -Is)"
  log_status "- Report: \`${out_base}_oldclaim/BREAKTHROUGH_REPORT.md\`"
}

run_wave() {
  local wave_start="$1"
  local wave_end=$(( wave_start + WAVE_SIZE - 1 ))
  log_status ""
  log_status "## Wave ${wave_start}-${wave_end}"
  log_status "- Started: $(date -Is)"
  local current_free
  current_free="$(free_gb)"
  log_status "- Free disk before wave: ${current_free}GB"
  if (( current_free < MIN_FREE_GB )); then
    log_status "- Abort: free disk ${current_free}GB below MIN_FREE_GB=${MIN_FREE_GB}GB."
    return 2
  fi

  local pids=()
  local gpu=0
  local seed="$wave_start"
  while (( seed <= wave_end )); do
    local s1="$seed"
    local s2=$(( seed + 1 ))
    local log_file="logs/bo24_${s1}_${s2}_${AUTONOMY_TAG}.log"
    (
      export CUDA_VISIBLE_DEVICES="$gpu"
      export DEVICE="${DEVICE:-cuda}"
      export ORACLE_DEVICE="${ORACLE_DEVICE:-cuda}"
      export ORACLE_INFERENCE_DEVICE="${ORACLE_INFERENCE_DEVICE:-cpu}"
      export EVAL_ORACLE_DEVICE="${EVAL_ORACLE_DEVICE:-cpu}"
      export PY
      bash scripts/run_v31_metpair_backbone_context_ortholinear_balancedobjective_seed_sweep_20260620.sh "$s1" "$s2"
    ) > "$log_file" 2>&1 &
    pids+=("$!")
    log_status "- GPU ${gpu}: seeds ${s1} ${s2}, log \`${log_file}\`"
    gpu=$(( gpu + 1 ))
    seed=$(( seed + 2 ))
  done

  local wave_status=0
  for pid in "${pids[@]}"; do
    if ! wait "$pid"; then
      wave_status=1
    fi
  done
  log_status "- Finished: $(date -Is), status=${wave_status}"
  aggregate_until "$wave_end"
  return "$wave_status"
}

log_status "# Balanced-Objective 24h Autonomous Run"
log_status ""
log_status "- Started: $(date -Is)"
log_status "- Time limit hours: ${AUTONOMY_HOURS}"
log_status "- Seed start: ${START_SEED}"
log_status "- Wave size: ${WAVE_SIZE}"
log_status "- Min free disk: ${MIN_FREE_GB}GB"

while (( $(date +%s) < END_TS )); do
  if ! run_wave "$NEXT_SEED"; then
    log_status "- Wave ${NEXT_SEED}-$(( NEXT_SEED + WAVE_SIZE - 1 )) returned nonzero; continuing after aggregation."
  fi
  NEXT_SEED=$(( NEXT_SEED + WAVE_SIZE ))
  if (( $(date +%s) >= END_TS )); then
    break
  fi
  sleep "$SLEEP_BETWEEN_WAVES"
done

log_status ""
log_status "- Completed autonomy window at: $(date -Is)"
